# Generated by Django 4.1.7 on 2023-02-23 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
